- docs/create_equinix_cluster.md
Adds docs for manually creating a cluster with CAPI / CAPEM to try things out while we work on the pipeline design.
I've added comments for decisions I'm not sure on or that are worth highlighting.
One thing to note is the Kubernetes API will be public. As we've discussed as a later step we could make it private and use a GitOps tool like Flux to manage the components running in the cluster.
> docs: Manually create Equinix cluster

- docs/create_equinix_cluster.md
Added info about creating a kind cluster for the manager cluster.  
Added info about the ssh-key needing to be created in the console for the project.
> Updated equinix metal manual docs

- clusters/kepler.yaml
References
- https://fluxcd.io/flux/components/helm/helmreleases/#install-configuration
- https://artifacthub.io/packages/helm/kepler/kepler
we need `--create-namsepace` flag to be true according to the docs
- Closes #15
Do remove the `clusters/kube-prometheus.yaml` as its been worked on by #12
> flux: based helm install of kepler

- docs/install_kepler.md
Some minor edits to the kepler docs @dipankardas011 @nikimanoledaki @AntonioDiTuri PTAL
> Kepler docs edits

- clusters/base/kube-prometheus-stack.yaml
- clusters/base/monitoring-namespace.yaml
Fix for error we hit in https://github.com/cncf-tags/green-reviews-tooling/actions/runs/7628160767
The kepler dashboard configmap is created by Flux so we need to create the namespace.
> Create monitoring namespace

- clusters/projects/falco/falco.yaml
Add Falco flux deployment config.
@nikimanoledaki first time using Flux. Looking forward to hearing more tips from you and happy to make any necessary adjustments.
Our new dedicated repo contains relevant docs https://github.com/falcosecurity/cncf-green-review-testing
Action Items:
Tracking:
- https://github.com/falcosecurity/cncf-green-review-testing/issues/4
CC Falco maintainers @leogr @LucaGuerra @maxgio92
> new(falco): add flux deployment config

- infrastructure/equinix-metal/main.tf
Prep for https://github.com/cncf-tags/green-reviews-tooling/issues/31 this enables traefik so we can use it for Ingress for Grafana
> Enable traefik ingress controller

- infrastructure/equinix-metal/main.tf
See https://github.com/cncf-tags/green-reviews-tooling/issues/8
Uses new S3 bucket created in CNCF's AWS account.
@leonardpahlke Can you update the GH secrets? This can then be merged.
> Use updated S3 bucket name

- clusters/base/kube-prometheus-stack.yaml
Towards https://github.com/cncf-tags/green-reviews-tooling/issues/31
Add ingress to Grafana in kube-prometheus-stack.yaml
Replaces https://github.com/cncf-tags/green-reviews-tooling/pull/42 from @greenscale-nandesh as a workaround to  problem with signed commits
> feat: Exposing Grafana dashboards publicly accessible from cluster

- infrastructure/equinix-metal/main.tf
- infrastructure/equinix-metal/variables.tf
kind/feature
- Makes node labels configurable so we can run Falco and monitoring stack on different nodes.
- Makes Equinix metal plan (their name for instance type) configurable so we can run larger nodes when needed
https://deploy.equinix.com/developers/docs/metal/hardware/standard-servers/
Towards https://github.com/cncf-tags/green-reviews-tooling/issues/30 and unblocks https://github.com/cncf-tags/green-reviews-tooling/pull/44
> feat: Make node labels and plan configurable

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- README.md
Closes #14
- Add `CONTRIBUTING.md` to clarify how to contribute
- Add PR Template
- Add instructions for signing commits & adding GPG-verification
> Add PR template & contributing guide

- clusters/flux-system/kustomization.yaml
- clusters/flux-system/node-selector-patch.yaml
Adds node selectors to the Flux deployments so they run on our internal node and not the Falco node that we are measuring energy consumption.
Fixes https://github.com/cncf-tags/green-reviews-tooling/issues/30
> feat: Add node-selector to flux deployments

- clusters/projects/falco/microservices-demo.yaml
kind/bug
The microservices demo wasn't deployed because of a typo in the chart name.
```
k get helmcharts.source.toolkit.fluxcd.io -n falco falco-online-boutique
NAME                    CHART             VERSION   SOURCE KIND      SOURCE NAME       AGE   READY   STATUS
falco-online-boutique   online-boutique   *         HelmRepository   online-boutique   20d   False   chart pull error: failed to get chart version for remote reference: could not get tags for "online-boutique": unable to locate any tags in provided repository: oci://us-docker.pkg.dev/online-boutique-ci/charts/online-boutique
```
See https://github.com/GoogleCloudPlatform/microservices-demo/tree/main/helm-chart
> fix: Helm chart name in microservices demo helmrelease

- CONTRIBUTING.md
- docs/proposals/README.md
- docs/proposals/proposal-000-template.md
`kind/documentation`
* Creates a proposal process through this repo
* Changes to proposals / design docs can be tracked through git
* Adds template with instructions (inspired by KEP/ADRs)
* Helps to deprecate the design doc (which doesn't scale well)
https://github.com/cncf-tags/green-reviews-tooling/issues/47
Please let me know what you think about creating a proposal process through this repository. It's similar to the KEP process in Kubernetes or ADRs which is widely used in OSS. Going through git would allow a better tracking of the history of proposals and how they change. It would also help to have discussions on individual points via PRs.
> Add proposal process

- infrastructure/equinix-metal/main.tf
- infrastructure/equinix-metal/variables.tf
kind/feature
This creates an Equinix elastic IP named `monitoring` and assigns it to the node where Grafana is deployed.
This will allow us to request a DNS record for `green-reviews.tag-env-sustainability.cncf.io`
Towards https://github.com/cncf-tags/green-reviews-tooling/issues/31
- Elastic IPs are not automatically added so this is done using `netplan` since the machines run Ubuntu
https://deploy.equinix.com/developers/docs/metal/networking/elastic-ips/#host-ip-configuration
- The elastic IP is also configured with K3s by setting the `--node-external-ip` flag
https://docs.k3s.io/cli/agent#networking
- With this Grafana is accessible in my test cluster at the external IP
```
k get no -o wide
NAME                              STATUS   ROLES                  AGE   VERSION …
```
> feat: Add elastic ip for Grafana

- docs/infrastructure/README.md
Adds link to Grafana explore page to be able to query prometheus without port forwarding.
None
> docs: Add explore link to Prometheus docs

- clusters/base/falco-sci.yaml
kind/feature
This PR adds the scaffolding for a Grafana dashboard that shows the SCI of Falco. There are still a few TODOs! I wanted to get early feedback on the progress @raymundovr and I have made so far.
The dashboard can be found [here]( http://147.75.40.83/d/fb32062b-eb1c-414a-965a-c529d39ef2be/falco-software-carbon-intensity-sci-index?orgId=1). Checkout the login info for the public Grafana instance [here](https://github.com/cncf-tags/green-reviews-tooling/blob/main/docs/infrastructure/README.md#monitoring).
Part of https://github.com/cncf-tags/green-reviews-tooling/issues/38
Part of https://github.com/cncf-tags/green-reviews-tooling/issues/39
^ not closing either until docs are added.
-->
Will open a separate PR for adding info to docs :)
> Add SCI dashboard for Falco

- docs/measurement/sci.md
Fixes https://github.com/cncf-tags/green-reviews-tooling/issues/38
> Add Energy (E) to documentation

- docs/measurement/sci.md
Fixes https://github.com/cncf-tags/green-reviews-tooling/issues/41
> Add docs for Falco functional unit

- CODEOWNERS
Adds CODEOWNERS file to automate setting of reviewers in PRs
None
Hey @leonardpahlke @guidemetothemoon,
we would like to add this automation so its clear who should review PRs and so we can spread the reviews across the team.
Are you OK with this?
I'm also going to need some help to enable it as I don't have access to the branch protection settings.
> Add codeowners for PR automation

- .github/workflows/project-trigger.yml
- .gitignore
- projects/projects.json
- scripts/project-trigger.sh
kind/feature
- Improvises on #104 
- Fixes #98
> feat: Trigger other Benchmark workflows

- .github/workflows/benchmark-pipeline.yaml
kind/bug
- Adds quoting to echo statement when creating kubeconfig from secret
- Adds a sleep for 10 seconds before kubectl wait command to allow flux resources to be created.
Follow up to #99 
cc @dipankardas011
> fix: Quote kubeconfig and add sleep to deploy step

- docs/proposals/proposal-001-trigger-and-deploy.md
Update proposal 1 to 
- Make releases check weekly instead of hourly. As we feel hourly is too often.
- Use releases endpoint instead of Atom feed
- Use JSON not YAML for projects metadata to avoid need for Go YAML library
Also adds missing link to atom feed.
None
cc @dipankardas011
> fix: Updates to proposal 1

- .github/workflows/benchmark-pipeline.yaml
- .github/workflows/project-trigger.yml
- .github/workflows/tofu.yaml
kind/bug
- Only run project trigger workflow for changes to scripts dir.
- Tidy up workflow naming for consistency
None
> fix: Only trigger on script changes and align naming

- docs/proposals/proposal-001-trigger-and-deploy.md
Updates proposal 1 (deploy) to be in sync with proposal 2 (run). 
Benchmark pipeline is renamed to project workflow and is named after the CNCF project e.g. `falco-pipeline.yaml`.
None
See https://github.com/cncf-tags/green-reviews-tooling/pull/93/files#r1662945563 for previous discussion.
> docs: Rename project workflow in deploy proposal

- .github/workflows/benchmark-pipeline.yaml
- projects/projects.json
- scripts/project-trigger.sh
This PR adds the new field  `benchmark_path` to project.json and adds a new job to the benchmark pipeline that uses the specified path.
Fixes #118
> Add benchmark_path field to projects data and benchmark-job to pipeline. (#118)

- .github/workflows/project-trigger.yml
kind/bug
The project trigger action runs for some pull requests e.g. #127 but it uses a GH secret that is not accessible from forked repos. 
So it fails which is confusing when reviewing. This disables the action for pull requests only.
Fixes #129
> fix: Don't run trigger on PR as secret not available

- .github/workflows/benchmark-pipeline.yaml
- projects/projects.json
- scripts/project-trigger.sh
kind/feature
It will give us a alternative route to use kubernetes manifests for the benchmark jobs instead of reusing github workflow.
With this we are trying to use the manifest location in github or any public facing endpoint from where we can get them
Addresses part of #121
Created this for finding alternative route for the current proposal 2 impl
Refer: #124, https://github.com/cncf-tags/green-reviews-tooling/issues/121#issuecomment-2476378468
> [Implementation] (Proposal 2)  Add Benchmark Pipeline 

- clusters/base/pipeline-kubeconfig-resources.yaml
kind/bug
Fix for `error: no matching resources found` when waiting for pods
https://github.com/cncf-tags/green-reviews-tooling/actions/runs/12071256142
> fix: Add perms for watching pods to pipeline role

- .github/workflows/benchmark-pipeline.yaml
kind/bug
Fix for pipeline as without namespace `kubectl wait` fails
```
k --kubeconfig /tmp/pipeline-kubeconfig wait pod \
--all \
--for=condition=Ready
error: no matching resources found
```
```
k --kubeconfig /tmp/pipeline-kubeconfig wait pod \
--all \
--for=condition=Ready \
--namespace=falco
pod/falco-event-generator-7f74b9cf77-s52fk condition met
pod/redis-7d65c855db-wtgk5 condition met
pod/stress-ng-85b4869f47-d72tj condition met
```
> fix: Add namespace to kubectl wait

- .github/workflows/benchmark-pipeline.yaml
- scripts/project-trigger.sh
kind/bug
- Fixes incorrect param name in trigger script.
- Adds sleeps before wait in case there is a delay creating pods.
- Fixes namespace when waiting for falco pods.
> fix: Benchmark param name and add sleep prior to kubectl wait

- .github/workflows/benchmark-pipeline.yaml
kind/bug
This PR updates the concurrency behavior of the benchmark pipeline to address issues with job cancellations when multiple workflows are triggered simultaneously. Previously, only two pipelines could run at a time, and additional workflows were canceled due to the default concurrency settings.
Fixes #142 
Since this if for a workflow where I don't have the secrets/permissions to trigger, we'll need to verify that this change produces the desired behavior once the pipeline is triggered. According to the documentation, it should.
> Changing concurrency behavior to allow for queued pipelines

- docs/proposals/proposal-002-run.md
Updates proposal 2 with design changes implemented in #127 
Fixes #117
Changes are quite big so sorry the diff is hard to follow. 
I also changed the diagram to mermaid based on the diagram @dipankardas011 added to proposal 1.
> docs: Update proposal 2 with design changes
