cncf-tags/green-reviews-tooling

docs/read-only-kubeconfig.md, scripts/gen-readonly-kubeconfig.sh
it adds a script for genrating readonly permissions for pods
- Closes #18
cc @nikimanoledaki
=> Script to generate readonly kubeconfig

infrastructure/equinix-metal/main.tf, infrastructure/equinix-metal/variables.tf
=> Fix setting plan for worker nodes

docs/infrastructure/README.md
kind/bug
Updates IP after networking changes in https://github.com/cncf-tags/green-reviews-tooling/pull/68
=> fix: Update Grafana URL

docs/README.md, docs/measurement/README.md, docs/measurement/sci.md
Adds documentation for M (embodied carbon) calculation using data from Boavizta API.
This is a write up of #40 so we can use the value for M in our SCI dashboard.
Fixes #40
If direction is OK here I can extend the docs to cover the other factors in the SCI calculation.
=> Add SCI docs for M (embodied carbon)

clusters/base/falco-sci.yaml
kind/bug
It fixes the file name in the ConfigMap for the Falco SCI dashboard
#33
=> Fix dashboard name in ConfigMap

docs/measurement/sci.md
Adds docs for carbon intensity (I) for the value used in the SCI dashboard
Towards https://github.com/cncf-tags/green-reviews-tooling/issues/39
=> docs: Add carbon intensity to SCI docs

.gitignore, clusters/base/kepler.yaml, clusters/base/kube-prometheus-stack.yaml, docs/infrastructure/cluster-infra-development.md, infrastructure/equinix-metal/variables.tf
=> Upgrade flux and use latest api versions

clusters/base/falco-sci.yaml, website/content/docs/measurement/sci.md
Equinix has recently published a new value for the PUE of their data centers from their 2023 report. The current value is not up to date with it.
None
=> Update PUE for equinix data centers according to 2023 report

CODEOWNERS
kind/bug
None
Current rules have a list of known file extensions that WG Green Reviews leads can approve.
New file extensions need an approval from TAG ENV leads. This is proving inflexible. e.g. #88 where we need to add an .svg diagram.
=> fix: Update CODEOWNERS to remove file extensions

.github/workflows/benchmark-pipeline.yaml, projects/projects.json, scripts/project-trigger.sh
This PR renames "sub components" to "config" just as described in [this](https://github.com/cncf-tags/green-reviews-tooling/pull/102/files) fix. Basically with these changes we reach better clarity because the three drivers needed for Falco are technically not subcomponents but rather configurations.
Fixes #110 
cc. @AntonioDiTuri / @rossf7
=> Rename sub components to configs and update scripts (#110)

docs/proposals/proposal-001-trigger-and-deploy.md
it helps in collaboration in diagrams and also dynamic diagram which can easily be updated in changing environment
=> enhancement: proposal-1 design diagram 

projects/falco/ebpf.yaml, projects/falco/kmod.yaml, projects/falco/modern-ebpf.yaml, scripts/project-trigger.sh
kind/bug
- Fixes input name in project trigger script.
- Sets kustomize paths for which falco config to apply.
None
CI error is expected because my fork can't access the repo secrets.
=> fix: Config input name and set kustomize paths

docs/local-setup/README.md, docs/proposals/proposal-003-report.md
Adds draft of proposal 3 to detail how and what metrics to record from the carbon emissions benchmark pipelines.
Fixes #95 
I am not so good at this style of writing as I’m generally a more direct writer. I am also not sure what level of detail to add as a lot of what I have in the design details reproduces other proposals, but I needed somewhere to record the steps I have to follow. It could be all that’s needed are the steps for deciding the metrics and exporting them, which makes everything fairly simple. But I’m not sure, and then the document really doesn’t need much detail, and possibly I can ignore a lot of the headings.
=> Add draft of proposal 3

docs/proposals/proposal-003-report.md
Extends proposal 3 draft after discussion in latest meeting.
I added a new metadata section as well as the sections on collecting and storing results.
For collecting and storing there are multiple options with pros and cons. When we narrow down the options I'll update the proposal.
=> docs: Extend draft of proposal 3 - Report

docs/proposals/proposal-003-report.md
Extends proposal 3 with git interim solution and example JSON file.
=> docs: Extend proposal 3 with git interim solution

.github/workflows/benchmark-pipeline.yaml
It adds the github step summary on the workflows having `on.workflow_dispatch`. It improves visibility on what input data it got triggered
None
=> enhancement: added a summary for gh workflow having event of workflow_dispatch

clusters/base/falco-namespace.yaml
kind/bug
temporary bug fix to check that everything else is working in the pipeline. this namespace will be removed once the manifests are changed upstream.
=> Add 'falco' namespace

.github/workflows/benchmark-pipeline.yaml
kind/bug
- temporary fix while we wait on https://github.com/falcosecurity/cncf-green-review-testing/pull/22
- adds `falco` as a choice in workflow input
=> Deploy falco to `falco` namespace temporarily

README.md
Updating the roadmap planning process to be more flexible / agile and less waterfall.
Now that we have a board, we can add issues to it directly: https://github.com/orgs/cncf-tags/projects/5/views/7
=> Update Roadmap process in README.md

.github/workflows/benchmark-pipeline-test.yml, main.go, projects/falco/ebpf.yaml, projects/falco/kmod.yaml, projects/falco/modern-ebpf.yaml
kind/bug
There are some breaking changes in the latest Falco release (0.40.0) we need to integrate.
See https://falco.org/blog/falco-0-40-0/#breaking-changes-and-deprecations
~~Needs https://github.com/falcosecurity/cncf-green-review-testing/pull/23 to be merged first.~~ EDIT: Merged
I also made some fixes for the integration test that I missed in my previous PR. I'll add comments for those.
=> fix: Support latest falco release and fixes for integration test

CONTRIBUTING.md, README.md
Adding some links to the documentation on how to run locally so they can be easily found for new contributors.
Easing path to contribute.
=> docs: Added links on how to run locally for development

.github/workflows/benchmark-pipeline.yaml, .gitignore, infrastructure/oracle-cloud/main.tf, infrastructure/oracle-cloud/scripts/clean_iptables.sh, infrastructure/oracle-cloud/scripts/start_k3s_server.sh, infrastructure/oracle-cloud/variables.tf
kind/feature
Fixes https://github.com/cncf-tags/green-reviews-tooling/issues/166
Example run https://github.com/rossf7/green-reviews-tooling/actions/runs/14843083377/job/41670459882
=> feat: Provision oracle cloud bare metal node
